// app/layout.tsx (Server Component)
import type { Metadata } from "next";
import ClientRootLayout from "./ClientRootLayout"; // This will contain your current layout logic

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientRootLayout>{children}</ClientRootLayout>
      </body>
    </html>
  );
}
